apps/elecciones/urls.py
from django.conf.urls import patterns, include, url
from .views import RegistrarEleccion, ListarEleccion, BorrarEleccion, EditarEleccion, tipo_ajax
from django.contrib.auth.decorators import login_required


"""
    Urls para ingresar a la aplicacion elecciones, permitiendo visualizar los registros, crearlos, editarlos, eliminarlos
"""
urlpatterns = patterns('',
                       url(r'^$', login_required(ListarEleccion.as_view(template_name="elecciones/listar.html"),
                                                 login_url='/'), name='listar_eleccion'),
                       url(r'^registrareleccion/', 'apps.elecciones.views.RegistrarEleccion',
                           name="registrar_eleccion",),
                       url(r'^editareleccion/(?P<pk>\d+)/$', 'apps.elecciones.views.EditarEleccion',
                           name="editar_eleccion",),
                       url(r'^borrareleccion/(?P<pk>\d+)/$', login_required(BorrarEleccion.as_view(template_name="elecciones/borrar.html"),
                                                                            login_url='/'), name='borrar_eleccion'),
                       url(r'^tipo_ajax/$', 'apps.elecciones.views.tipo_ajax', name='tipo_ajax',),

                       )

apps/urls.py
from django.conf.urls import patterns, include, url
#from apps.configuraciones.views import Configuraciones

urlpatterns = patterns('',
                       #url(r'^$', include('apps.inicio.urls')),
                       url(r'^', include('apps.login.urls')),
                       url(r'^menu/', include('apps.menu.urls')),
                       url(r'^configuraciones/', include('apps.configuraciones.urls')),
                       url(r'^partidos/', include('apps.partidos.urls')),
                       url(r'^elecciones/', include('apps.elecciones.urls')),
                       url(r'^exitpoll/', include('apps.exitpoll.urls')),
                       url(r'^candidatos/', include('apps.candidatos.urls')),
                       url(r'^reportes/', include('apps.reportes.urls')),
                       url(r'^encuestas/', include('apps.registro.encuestas.urls')),
                       url(r'^preguntas/', include('apps.registro.preguntas.urls')),
                       url(r'^respuestas/', include('apps.registro.respuestas.urls')),
                       url(r'^aplicada/', include('apps.aplicada.urls')),
                       )

exit_poll/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from rest_framework.routers import DefaultRouter
from apps.topologia.estados.viewsets import EstadoViewSet
from apps.topologia.municipios.viewsets import MunicipioViewSet
from apps.topologia.parroquias.viewsets import ParroquiaViewSet
#from apps.topologia.sectores.viewsets import SectorViewSet
#from apps.topologia.poligonales.viewsets import PoligonalViewSet
from apps.circuitos.viewsets import CircuitoViewSet
from apps.grupo_etareo.viewsets import Grupo_EtareoViewSet
from apps.tipos.categoria_eleccion.viewsets import CategoriaViewSet
from apps.tipos.tipo_eleccion.viewsets import Tipo_eleccionViewSet
from apps.partidos.viewsets import PartidosViewSet
from apps.elecciones.viewsets import EleccionViewSet
from apps.exitpoll.viewsets import ExitPollViewSet
from apps.registro.encuestas.viewsets import EncuestaViewSet
from apps.candidatos.viewsets import CandidatosViewSet
from apps.registro.preguntas.viewsets import PreguntasViewSet
from apps.registro.respuestas.viewsets import RespuestasViewSet
import settings


router = DefaultRouter()
router.register(r'estado', EstadoViewSet)
router.register(r'municipio', MunicipioViewSet)
router.register(r'parroquia', ParroquiaViewSet)
#router.register(r'sector', SectorViewSet)
#router.register(r'poligonal', PoligonalViewSet)
router.register(r'circuito', CircuitoViewSet)
router.register(r'grupo_etareo', Grupo_EtareoViewSet)
router.register(r'categoria_eleccion', CategoriaViewSet)
router.register(r'tipo_eleccion', Tipo_eleccionViewSet)
router.register(r'partidos', PartidosViewSet)
router.register(r'elecciones', EleccionViewSet)
router.register(r'exitpoll', ExitPollViewSet)
router.register(r'candidatos', CandidatosViewSet)
router.register(r'encuestas', EncuestaViewSet)
router.register(r'preguntas', PreguntasViewSet)
router.register(r'respuestas', RespuestasViewSet)

urlpatterns = patterns('',
                       url(r'^chaining/', include('pixelfields_smart_selects.urls')),
                       url(r'^admin/', include(admin.site.urls)),
		       url(r'^login/', include('apps.login.urls')),
                       url(r'^api/', include(router.urls)),
                       url(r'^', include('apps.urls')),
                       url(r'^imagenes/(?P<path>.*)$', 'django.views.static.serve',
                           {'document_root': settings.MEDIA_ROOT}),
		       url(r'^', include('apps.exitpoll.urls')),
                       url(r'^', include('apps.votacion.urls')),
                       url(r'^reporte/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_PDF}),
		       url(r'^temporal/', include('apps.temporal.urls')),
                       )

apps/elecciones/models.py
# -*- coding: utf-8 -*-
from django.db import models
from smart_selects.db_fields import ChainedForeignKey
from apps.tipos.categoria_eleccion.models import Categoria
from apps.tipos.tipo_eleccion.models import Tipo_eleccion
import datetime
from django.contrib.auth.models import User


class Eleccion(models.Model):
    """ Clase que define todo lo referente a la Informacion del proceso `Electoral`:
    Registrar, Modificar, Eliminar y Consultar

    :param CharField nombre: El nombre del proceso Electoral
    :param ForeignKey categoria_eleccion: La categoria que abarca la eleccion
    :param IntegerField tipo_eleccion: Tipo de eleccion segun la categoria que seleccione

    :param ForeignKey user_create: campo que llama al modelo User.
    :param ForeignKey user_update: campo que llama al modelo User.
    :param DateTimeField fecha_create: campo de tipo tiempo que captura fecha y hora.
    :param DateTimeField fecha_update: campo de tipo tiempo que captura fecha y hora.
    """
    #Informacion Principal
    nombre = models.CharField(verbose_name="Nombre del Proceso Electoral", max_length=100)
    categoria_eleccion = models.ForeignKey(Categoria)
    tipo_eleccion = models.IntegerField(null=True)
    ele_activa = models.BooleanField(default=False)
    #Auditoria
    user_create = models.ForeignKey(User, null=True, blank=True, related_name='+')
    user_update = models.ForeignKey(User, null=True, blank=True, related_name='+')
    fecha_create = models.DateTimeField(auto_now_add=True, auto_now=False)
    fecha_update = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)

    class Meta:
        unique_together = ("nombre",)
        ordering = ('nombre',)

    def __unicode__(self):
        #return: Representacion en cadena de la clase Partidos
        return self.nombre

    def get_absolute_url(self):
        return ('listar_eleccion', [self.id, ])

apps/elecciones/forms.py
#encoding:utf-8
from django.forms import ModelForm
from django import forms
from apps.elecciones.models import Eleccion


class EleccionForm(forms.ModelForm):
    """ Clase de donde se define la estructura del formulario `Eleccion`"""
    class Meta:
        model = Eleccion

apps/elecciones/views.py
# -*- encoding: utf-8 -*-# -*- encoding: utf-8 *

from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Eleccion
from django.shortcuts import render, render_to_response, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext
from .forms import EleccionForm
from apps.tipos.categoria_eleccion.models import Categoria
from apps.tipos.tipo_eleccion.models import Tipo_eleccion
from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from apps.exitpoll.models import ExitPoll


@login_required(login_url='/')
def RegistrarEleccion(request):
    """ Vista basada en Metodos o funciones: (`Registrar`). """
    list_categoria = Categoria.objects.all()  # Modelo de consulta a Categoria
    list_tipo = Tipo_eleccion.objects.all()  # Modelo de consulta a Tipo_eleccion
    if request.method == 'POST':
        bandera = request.POST.get('bandera')
        nombre = request.POST.get('nombre')
        categoria = request.POST.get('categoria_eleccion')
        tipo_eleccion = request.POST.get('tipo_eleccion')
        existe = Eleccion.objects.filter(nombre=nombre).exists()
        if existe and bandera == 'true':
            return HttpResponse('existe')
        else:
            form_reg_eleccion = EleccionForm(request.POST, request.FILES)
            if form_reg_eleccion.is_valid():
                new_reg_eleccion = form_reg_eleccion.save(commit=False)
                new_reg_eleccion.save()
            return HttpResponseRedirect('/elecciones/')
    else:
        form_reg_eleccion = EleccionForm()
    ctx = {'form_reg_eleccion': form_reg_eleccion, 'list_categoria': list_categoria,
           'list_tipo': list_tipo}  # ctx = Contexto
    return render_to_response('elecciones/eleccion.html',
                              ctx, context_instance=RequestContext(request))


@login_required(login_url='/')
def EditarEleccion(request, pk):
    """ Vista basada en Metodos o funciones: (`Modificar`)."""
    list_categoria = Categoria.objects.all()  # Modelo de consulta a Categoria
    list_tipo = Tipo_eleccion.objects.all()  # Modelo de consulta a Tipo_eleccion
    obj_eleccion = Eleccion.objects.get(id=pk)
    if request.method == 'POST':
        form_eleccion = EleccionForm(request.POST, request.FILES, instance=obj_eleccion)
        if form_eleccion.is_valid():
            edit_regelector = form_eleccion.save(commit=False)
            edit_regelector.save()
            return HttpResponseRedirect('/elecciones/')
    else:
        form_eleccion = EleccionForm(instance=obj_eleccion)
    ctx = {'form_eleccion': form_eleccion, 'obj_eleccion': obj_eleccion, 'list_categoria': list_categoria,
           'list_tipo': list_tipo, }
    return render_to_response('elecciones/modificar.html',
                              ctx, context_instance=RequestContext(request))


def tipo_ajax(request):
    id_cat = request.GET['id']
    tipo = Tipo_eleccion.objects.filter(categoria_id=id_cat)
    data = serializers.serialize('json', tipo, fields=('id', 'tipo'))

    return HttpResponse(data, content_type='application/json')


class ListarEleccion(ListView):
    """ Vista basada en clase: (`Listar`)

    :param template_name: ruta de la plantilla
    :param model: Modelo al cual se hace referencia
    :param context_object_name: nombre del objeto que contiene esta vista

    """
    model = Eleccion
    template_name = 'elecciones/listar.html'
    context_object_name = "listar_eleccion"
    form_class = EleccionForm

    def post(self, request, *args, **kwargs):

        pk_usuario = self.request.POST.get('pk')
        status = self.request.POST.get('status')

        #Validamos el status
        if status == 'false':
            status = False
        else:
            status = True

        #Buscamos el id(pk) del usuario en el modelo de Usuario
        eleccion = Eleccion.objects.filter(id=pk_usuario)
        eleccion.update(
            ele_activa=status
        )
        return HttpResponse('exito')

    def get_context_data(self, **kwargs):
        # Llamamos ala implementacion para traer un primer context
        context = super(ListarEleccion, self).get_context_data(**kwargs)
        # Agregamos un QuerySet
        context['list_t'] = Tipo_eleccion.objects.all()
        return context


class BorrarEleccion(DeleteView):
    """ Vista basada en clase: (`Borrar`)

    :param template_name: ruta de la plantilla
    :param model: Modelo al cual se hace referencia
    :param success_url: nombre de la ruta a la cual se redireccionara la aplicacion una vez eliminado el registro
         satisfactoriamente.
    :param context_object_name: nombre del objeto que contiene esta vista
    """
    model = Eleccion
    template_name = 'elecciones/borrar.html'
    context_object_name = "borrar_eleccion"
    success_url = reverse_lazy("listar_eleccion")

    def get_context_data(self, **kwargs):
        context = super(BorrarEleccion, self).get_context_data(**kwargs)
        id_ele = self.kwargs['pk']
        ele = ExitPoll.objects.all()
        existe = ele.filter(eleccion_id=id_ele)
        cantidad = len(existe)
        
        context['cantidad'] = cantidad
        return context

templates/elecciones/borrar.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block contenido %}
<html>
<head>
    <title>Eliminar Eleccion</title>
</head>
{% load templatag_grupos %}
{% ifusergroup Registro %}
<script>
$(document).ready(function() {
    $('#volver').click(function(){
        url = '/elecciones/'
        window.location = url
    })
});
</script>
<body>
    <br/>
    <br/>
   <label class="tit-elim">Eliminar Elección</label>
    <form method="post">
	{% csrf_token %}
	<h3>¿Está seguro que quiere borrar esta eleccion "{{ borrar_eleccion }}" ?</h3>
	{% if cantidad > 0 %}
	    <h4>Disculpe, pero no puede Eliminar esta Elección porque ya fue <span style="color: red"> vinculado a 1 o más candidato(s) para el Proceso de Votación</span></h4>
	{% endif%}
	<button style="font-weight: bold;font-size: 13px" type="button" id="volver" class="btn btn-warning"/>
	    <span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Volver
	</button>
	<button style="font-weight: bold;font-size: 13px" type="submit" id="eliminar" class="btn btn-danger"
	    {% if cantidad > 0 %}
		    disabled="disabled" 
		{% endif %}
	    /><span class="glyphicon glyphicon-remove"></span>&nbsp;Eliminar
	</button>
	
    </form>
</body>
{% else %}
<p style="color: #FF0000; font-size: 18px">Disculpe No esta autorizado para esa área.</p>
{% endifusergroup %}
</html>
{% endblock %}

templates/elecciones/eleccion.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block contenido %}
<html>
<head>
    <title>Registrar Elección</title>
</head>
{% load templatag_grupos %}
{% ifusergroup Registro %}
<script type="text/javascript">
$(document).ready(function(){
    $("#id_categoria_eleccion,#id_tipo_eleccion").select2();
    $('#id_nombre').alphanumeric({allow:" "});
    $('#registrar').click(function(e){ //Valida al guardar que el rago no sea menor 5 caracteres
	e.preventDefault();
	
	var categoria    = $('#id_categoria_eleccion').find('option').filter(':selected').val()
	var tipo    = $('#id_tipo_eleccion').find('option').filter(':selected').val()
	
	$('input').on({
	    keypress: function() {
		$(this).parent('div').removeClass('has-error');
	    }
	});

	
	if (($('#id_nombre').val() == '')) {
	    bootbox.alert('Disculpe, Debe Colocar el nombre de la Elección', function() {	    
		$('#id_nombre').parent('div').addClass('has-error');
	    }); 
	}
	else if (($('#id_nombre').val().length < 4)) {
	    bootbox.alert('Disculpe, Nombre de Elección invalido (muy corto)', function() {	    
		$('#id_nombre').parent('div').addClass('has-error');
	    });
	}
	else if($('#id_nombre').val() == null || $('#id_nombre').val().length == 0 || /^\s+$/.test($('#id_nombre').val())) {
            bootbox.alert('Disculpe, no esta registrando nada', function() {	    
		$('#id_nombre').parent('div').addClass('has-error');
	    });
        }
	else if (categoria == 0) {
    	    bootbox.alert('Disculpe, Debe Seleccionar la cateoria', function() {	    
		$('#id_categoria_eleccion').select2('open');
	    });  
	}
	else if (tipo == 0) {
	    bootbox.alert('Disculpe, Debe Seleccionar el Tipo de Elección', function() {	    
		$('#id_tipo_eleccion').select2('open');
	    });
	}
        else {
            $.post('',$('#form_eleccion').serialize()+'&bandera=true',function(response){
		if (response == 'existe') {
		    bootbox.alert('Disculpe, Esta eleccion Ya Existe', function() {	    
			$('#id_nombre').parent('div').addClass('has-error');
		    });
		}else{
		    $('#form_eleccion').submit(); 
		}
	    });
        }
    });
    $('#volver').click(function(){
        url = '/elecciones/'
        window.location = url
    })
    $('#limpiar').click(function(){
        $('#id_categoria_eleccion').select2('val', '0');
	$('#id_tipo_eleccion').select2('val', '0');
    })
    
});
</script>
<body>
    
   <form method="post" id="form_eleccion">
	{% csrf_token %}
	
    <br/>
    <br/>
 
	<div style="width: 80%;" class="panel panel-primary">
	    <div class="panel-heading">
	      <label class="panel-title">Registrar Elección</label>
	    </div>
	    <br/>
	      <fieldset><legend class="titulo">Datos de la Elección</legend></fieldset>
	      <br/>
	    <div class="form-inline" style="text-align: left;font-weight: bold;font-size: 13px">
		<div class="form-group col-xs-2">
		    <label>Nombre: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
		</div>
		<div class="form-group col-xs-4">
		    <input id="id_nombre" maxlength="100" placeholder="Nombre de la elección" style="width: 100%;bold;font-size: 13px" name="nombre" type="text" />
		</div>
		<div class="form-group col-xs-2">
		    <label>Categoría:</label>
		</div>
		<div class="form-group col-xs-4">
		    <select id="id_categoria_eleccion" style="width: 100%;bold;font-size: 13px" class="form-control select2 input-sm " name="categoria_eleccion">
			<option value="0">Seleccione</option>
			{% for e in list_categoria %}
			    <option value='{{e.id}}'>{{ e.categoria }}</option>
			{% endfor %}
		    </select>
		</div>
	    </div>
	    <br/>
	    <br/>
	    <br/>
	    <br/>
	    <div class="form-inline" style="text-align: left;font-weight: bold;font-size: 13px">
		<div class="form-group col-xs-2">
		    <label>Tipo de Elección:</label>
		</div>
		<div class="form-group col-xs-4">
		    <select id="id_tipo_eleccion" style="width: 100%;bold;font-size: 13px" class="form-control select2 input-sm " name="tipo_eleccion" >
			<option value="0">Seleccione</option>
		    </select>
		</div>
		<div class="form-group col-xs-2" style="text-align: left;font-weight: bold;font-size: 13px">
		    <label>Activa:&nbsp;&nbsp;</label>
		</div>
		<div class="form-group col-xs-4" style="text-align: left;">
		    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" id="id_activa" name="ele_activa" />
		</div>
	    </div>
	    <br/>
	    
	    <input id='user_create' type="hidden" name='user_create' value='{{ user.id }}'>
	    <br/>
	    <br/>
	    <br/>
	    <div class="row" style="text-align: center">
		<button type="button" id="volver" style="font-weight: bold;font-size: 13px" class="btn btn-warning " >
		    &nbsp;<span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Volver
		</button>
		<button type="submit" id="registrar" style="font-weight: bold;font-size: 13px" class="btn btn-info"/>
		    &nbsp;<span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;Registrar
		</button>
		<button type="reset" id="limpiar" style="font-weight: bold;font-size: 13px" class="btn btn-success"/>
		    &nbsp;<span class="glyphicon glyphicon-retweet"></span>&nbsp;&nbsp;Limpiar
		</button>
		
	    </div>
	    <br/>
	</div>
    </form>
</body>
{% else %}
<p style="color: #FF0000; font-size: 18px">Disculpe No esta autorizado para esa área.</p>
{% endifusergroup %}
</html>
{% endblock %}

templates/elecciones/modificar.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block contenido %}
<html>
<head>
    <title>Modificar Elección</title>
</head>
{% load templatag_grupos %}
{% ifusergroup Registro %}
<script type="text/javascript">
$(document).ready(function(){
    $("#id_categoria_eleccion,#id_tipo_eleccion").select2();
    $('#id_nombre').alphanumeric({allow:" "});
    $('#registrar').click(function(e){ //Valida al guardar que el rago no sea menor 5 caracteres
	e.preventDefault();
	
	var categoria    = $('#id_categoria_eleccion').find('option').filter(':selected').val()
	var tipo    = $('#id_tipo_eleccion').find('option').filter(':selected').val()
	$('input').on({
	    keypress: function() {
		$(this).parent('div').removeClass('has-error');
	    }
	});

	
	if (($('#id_nombre').val() == '')) {
	    bootbox.alert('Disculpe, Debe Colocar el nombre de la Elección', function() {	    
		$('#id_nombre').parent('div').addClass('has-error');
	    }); 
	}
	else if (($('#id_nombre').val().length < 4)) {
	    bootbox.alert('Disculpe, Nombre de Elección invalido (muy corto)', function() {	    
		$('#id_nombre').parent('div').addClass('has-error');
	    });
	}
	else if($('#id_nombre').val() == null || $('#id_nombre').val().length == 0 || /^\s+$/.test($('#id_nombre').val())) {
            bootbox.alert('Disculpe, no esta registrando nada', function() {	    
		$('#id_nombre').parent('div').addClass('has-error');
	    });
        }
	else if (categoria == 0) {
    	    bootbox.alert('Disculpe, Debe Seleccionar la cateoria', function() {	    
		$('#id_categoria_eleccion').select2('open');
	    });  
	}
	else if (tipo == 0) {
	    bootbox.alert('Disculpe, Debe Seleccionar el Tipo de Elección', function() {	    
		$('#id_tipo_eleccion').select2('open');
	    });
	}
	else{
	    $('form').submit();
	}

    });
    $('#volver').click(function(){
        url = '/elecciones/'
        window.location = url
    })
});
</script>
<body>
    <form method="post">
	{% csrf_token %}
    <br/>
    <br/>
   
	<div style="width: 80%;" class="panel panel-primary">
	    <div class="panel-heading">
	      <label class="panel-title" >Modificar Elección</label>
	    </div>
	    <br/>
	    <fieldset><legend class="titulo">Datos de la Elección</legend></fieldset>
	    <br/>
	    <div class="form-inline">
		<div class="form-group col-xs-2">
		    <label>Nombre: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
		</div>
		<div class="form-group col-xs-4">
		    <input id="id_nombre" maxlength="50" placeholder="Nombre de la elección" style="width: 100%;bold;font-size: 13px" value='{{obj_eleccion.nombre}}' name="nombre" type="text" />
		</div>
		<div class="form-group col-xs-2">
		    <label>Categoría:</label>
		</div>
		<div class="form-group col-xs-4">
		    <select id="id_categoria_eleccion" style="width: 100%;bold;font-size: 13px" class="form-control select2 input-sm " name="categoria_eleccion">
			<option value="">-------------- Seleccione --------------</option>
			{% for e in list_categoria %}
			    {% if e.id == obj_eleccion.categoria_eleccion_id %}
				<option value='{{e.id}}' selected='selected'>{{ e.categoria }}</option>
			    {% endif %}
			    {% if not e.id == obj_eleccion.categoria_eleccion_id %}
				<option value='{{e.id}}'>{{ e.categoria }}</option>
			    {% endif %}
			{% endfor %}
		    </select>
		</div>
	    </div>
	    <br/>
	    <br/>
	    <br/>
	    <div class="form-inline" >
		<div class="form-group col-xs-2">
		    <label>Tipo de Elección:</label>
		</div>
		<div class="form-group col-xs-4">
		    <select id="id_tipo_eleccion" style="width: 100%;bold;font-size: 13px" class="form-control select2 input-sm " name="tipo_eleccion" >
			<option value="">-------------- Seleccione --------------</option>
			{% for t in list_tipo %}
			    {% if t.id == obj_eleccion.tipo_eleccion %}
				<option value='{{t.id}}' selected='selected'>{{ t.tipo }}</option>
			    {% endif %}
			    {% if not t.id == obj_eleccion.tipo_eleccion %}
				<option value='{{t.id}}'>{{ t.tipo }}</option>
			    {% endif %}
			{% endfor %}
		    </select>
		</div>
		<div class="form-group col-xs-2" style="text-align: left;font-weight: bold;font-size: 13px">
		    <label>Activa:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
		</div>
		<div class="form-group col-xs-4" style="text-align: left;">
		    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		    <input type="checkbox" id="id_activa" name="ele_activa"
		    {% if obj_eleccion.ele_activa == True %}
			   checked="checked"
		    {% endif %}
		    />
		</div>
	    </div>
	    <br/>
	    <br/>
	   
	    <input id='edit_user_create' type="hidden" name='user_create' value="{{editar_tipos.user_create.id }}">
	    <input id='user_update' type="hidden" name='user_update' value='{{ user.id }}'>
	    <br/>
	    <br/>
	    <br/>
	    <div class="row" style="text-align: center">
		<button type="button" id="volver" style="font-weight: bold;font-size: 13px" class="btn btn-warning " >
		    &nbsp;<span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Volver
		</button>
		<button type="submit" id="registrar" style="font-weight: bold;font-size: 13px" class="btn btn-info"/>
		    &nbsp;<span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;Guardar Cambios
		</button>
	    </div>
	    <br/>
	</div>
	
	
	
    </form>
</body>
{% else %}
<p style="color: #FF0000; font-size: 18px">Disculpe No esta autorizado para esa área.</p>
{% endifusergroup %}
</html>
{% endblock %}