apps/registro/encuestas/urls.py
from django.conf.urls import patterns, include, url
from .views import ListarEncuesta, RegistrarEncuesta, BorrarEncuesta, FinalizarEncuesta, VerEncuesta, CerrarEncuesta
from django.contrib.auth.decorators import login_required


"""
    Urls para ingresar a la aplicacion Encuesta, permitiendo visualizar los registros, crearlos, editarlos, eliminarlos
"""
urlpatterns = patterns('',
                       url(r'^$', login_required(ListarEncuesta.as_view(template_name="registro/encuesta/listar.html"),
                                                 login_url='/'), name='listar_encuestas'),
                       url(r'^registrarencuesta/', 'apps.registro.encuestas.views.RegistrarEncuesta',
                           name="registrar_encuesta",),
                       url(r'^editarencuesta/(?P<pk>\d+)/$', 'apps.registro.encuestas.views.EditarEncuesta',
                           name='editar_encuesta',),
                       url(r'^borrarencuesta/$', login_required(BorrarEncuesta.as_view(),
                                                login_url='/'), name='borrar_encuesta'),
                       url(r'^finalizar/$', login_required(FinalizarEncuesta.as_view(),
                                                login_url='/'), name='finalizar_encuesta'),
                       url(r'^cerrar/$', login_required(CerrarEncuesta.as_view(),
                                                login_url='/'), name='cerrar_encuesta'),
                       url(r'^verencuesta/(?P<encuesta>\d+)$', login_required(VerEncuesta.as_view(),
                                                login_url='/'), name='ver_encuesta'),

                       )

apps/registro/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required


urlpatterns = patterns('',
                       url(r'^encuestas/', include('apps.registros.encuestas.urls')),
                       url(r'^preguntas/', include('apps.registros.preguntas.urls')),
                       url(r'^respuestas/', include('apps.registros.respuestas.urls')),
                       )

apps/urls.py
from django.conf.urls import patterns, include, url
#from apps.configuraciones.views import Configuraciones

urlpatterns = patterns('',
                       #url(r'^$', include('apps.inicio.urls')),
                       url(r'^', include('apps.login.urls')),
                       url(r'^menu/', include('apps.menu.urls')),
                       url(r'^configuraciones/', include('apps.configuraciones.urls')),
                       url(r'^partidos/', include('apps.partidos.urls')),
                       url(r'^elecciones/', include('apps.elecciones.urls')),
                       url(r'^exitpoll/', include('apps.exitpoll.urls')),
                       url(r'^candidatos/', include('apps.candidatos.urls')),
                       url(r'^reportes/', include('apps.reportes.urls')),
                       url(r'^encuestas/', include('apps.registro.encuestas.urls')),
                       url(r'^preguntas/', include('apps.registro.preguntas.urls')),
                       url(r'^respuestas/', include('apps.registro.respuestas.urls')),
                       url(r'^aplicada/', include('apps.aplicada.urls')),
                       )

exit_poll/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from rest_framework.routers import DefaultRouter
from apps.topologia.estados.viewsets import EstadoViewSet
from apps.topologia.municipios.viewsets import MunicipioViewSet
from apps.topologia.parroquias.viewsets import ParroquiaViewSet
#from apps.topologia.sectores.viewsets import SectorViewSet
#from apps.topologia.poligonales.viewsets import PoligonalViewSet
from apps.circuitos.viewsets import CircuitoViewSet
from apps.grupo_etareo.viewsets import Grupo_EtareoViewSet
from apps.tipos.categoria_eleccion.viewsets import CategoriaViewSet
from apps.tipos.tipo_eleccion.viewsets import Tipo_eleccionViewSet
from apps.partidos.viewsets import PartidosViewSet
from apps.elecciones.viewsets import EleccionViewSet
from apps.exitpoll.viewsets import ExitPollViewSet
from apps.registro.encuestas.viewsets import EncuestaViewSet
from apps.candidatos.viewsets import CandidatosViewSet
from apps.registro.preguntas.viewsets import PreguntasViewSet
from apps.registro.respuestas.viewsets import RespuestasViewSet
import settings


router = DefaultRouter()
router.register(r'estado', EstadoViewSet)
router.register(r'municipio', MunicipioViewSet)
router.register(r'parroquia', ParroquiaViewSet)
#router.register(r'sector', SectorViewSet)
#router.register(r'poligonal', PoligonalViewSet)
router.register(r'circuito', CircuitoViewSet)
router.register(r'grupo_etareo', Grupo_EtareoViewSet)
router.register(r'categoria_eleccion', CategoriaViewSet)
router.register(r'tipo_eleccion', Tipo_eleccionViewSet)
router.register(r'partidos', PartidosViewSet)
router.register(r'elecciones', EleccionViewSet)
router.register(r'exitpoll', ExitPollViewSet)
router.register(r'candidatos', CandidatosViewSet)
router.register(r'encuestas', EncuestaViewSet)
router.register(r'preguntas', PreguntasViewSet)
router.register(r'respuestas', RespuestasViewSet)

urlpatterns = patterns('',
                       url(r'^chaining/', include('pixelfields_smart_selects.urls')),
                       url(r'^admin/', include(admin.site.urls)),
		       url(r'^login/', include('apps.login.urls')),
                       url(r'^api/', include(router.urls)),
                       url(r'^', include('apps.urls')),
                       url(r'^imagenes/(?P<path>.*)$', 'django.views.static.serve',
                           {'document_root': settings.MEDIA_ROOT}),
		       url(r'^', include('apps.exitpoll.urls')),
                       url(r'^', include('apps.votacion.urls')),
                       url(r'^reporte/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_PDF}),
		       url(r'^temporal/', include('apps.temporal.urls')),
                       )

apps/registro/encuestas/models.py
# -*- coding: utf-8 -*-
'''Modelo para el Registro Poligonales'''
from django.db import models
from django.contrib.auth.models import User

STATUS = (
    ('1', "Borrador"),
    ('2', "Finalizada"),
    ('3', "Cerrada"),
)
TIPO = (
    ('1', "Web"),
    ('2', "Móvil"),
    ('3', "Web y Móvil"),
)


class Encuesta(models.Model):
    """ Clase que define todo lo referente a las 'Encuesta':
    Registrar, Modificar, Eliminar y Consultar

    :param ForeignKey user_create: campo que llama al modelo User.
    :param ForeignKey user_update: campo que llama al modelo User.
    :param DateTimeField fecha_create: campo de tipo tiempo que captura fecha y hora.
    :param DateTimeField fecha_update: campo de tipo tiempo que captura fecha y hora.
    """

    cod_encuesta = models.IntegerField(verbose_name="Código de Encuesta", max_length=4)
    nombre = models.CharField(verbose_name="Nombre de la Encuesta", max_length=150)
    estatus = models.CharField(choices=STATUS, default=1, max_length=2)
    tipo = models.CharField(choices=TIPO, max_length=2, null=True, blank=True)
    tipo_aplicacion = models.IntegerField(null=True)

    #Auditoria
    user_create = models.ForeignKey(User, null=True, blank=True, related_name='+')
    user_update = models.ForeignKey(User, null=True, blank=True, related_name='+')
    fecha_create = models.DateField(auto_now_add=True, auto_now=False)
    fecha_update = models.DateField(auto_now_add=False, auto_now=True, null=True)

    class Meta:
        """
        :param unique_together: verifica que no existan centros repetidos en base a su nombre codigo estado
            municipio y parroquia
        :param ordering: Ordena los registros en base a el campo cod_n nombre estado
        """
        unique_together = ("cod_encuesta", "nombre")
        #ordering = ('cod_encuesta')

    def __unicode__(self):
        return self.nombre

    def get_absolute_url(self):
        return ('listar_encuesta', [self.id, Encuesta])

apps/registro/preguntas/models.py
# -*- coding: utf-8 -*-
'''Modelo para el Registro Poligonales'''
from django.db import models
from django.contrib.auth.models import User

TIPO = (
    ('1', "Excluyente"),
    ('2', "No Excluyente"),
)


class Preguntas(models.Model):
    """ Clase que define todo lo referente a las 'Preguntas':
    Registrar, Modificar, Eliminar y Consultar

    :param ForeignKey user_create: campo que llama al modelo User.
    :param ForeignKey user_update: campo que llama al modelo User.
    :param DateTimeField fecha_create: campo de tipo tiempo que captura fecha y hora.
    :param DateTimeField fecha_update: campo de tipo tiempo que captura fecha y hora.
    """

    cod_encuesta = models.IntegerField(verbose_name="Código de Encuesta", max_length=4)
    cod_pregunta = models.IntegerField(verbose_name="Código de Pregunta", max_length=4)
    pregunta = models.CharField(verbose_name="Descripcion de la Pregunta", max_length=300)
    tipo = models.CharField(choices=TIPO, default=1, max_length=2)

    #Auditoria
    user_create = models.ForeignKey(User, null=True, blank=True, related_name='+')
    user_update = models.ForeignKey(User, null=True, blank=True, related_name='+')
    fecha_create = models.DateField(auto_now_add=True, auto_now=False)
    fecha_update = models.DateField(auto_now_add=False, auto_now=True, null=True)

    class Meta:

        unique_together = ("cod_pregunta", "pregunta")
 

    def __unicode__(self):
        return self.pregunta

    def get_absolute_url(self):
        return ('listar_preguntas', [self.id, Preguntas])

apps/registro/respuestas/models.py
# -*- coding: utf-8 -*-
'''Modelo para el Registro Poligonales'''
from django.db import models
from django.contrib.auth.models import User
from apps.registro.preguntas.models import Preguntas

TIPO = (
    ('1', "Cerrada"),
    ('2', "Abierta"),
)


class Respuestas(models.Model):
    """ Clase que define todo lo referente a las 'Respuestas':
    Registrar, Modificar, Eliminar y Consultar

    :param ForeignKey user_create: campo que llama al modelo User.
    :param ForeignKey user_update: campo que llama al modelo User.
    :param DateTimeField fecha_create: campo de tipo tiempo que captura fecha y hora.
    :param DateTimeField fecha_update: campo de tipo tiempo que captura fecha y hora.
    """

    cod_pregunta = models.ForeignKey(Preguntas)
    cod_respuesta = models.IntegerField(verbose_name="Código de Respuestas", max_length=4)
    respuesta = models.CharField(verbose_name="Descripcion de la Respuestas", max_length=200)
    tipo = models.CharField(choices=TIPO, default=1, max_length=2)

    #Auditoria
    user_create = models.ForeignKey(User, null=True, blank=True, related_name='+')
    user_update = models.ForeignKey(User, null=True, blank=True, related_name='+')
    fecha_create = models.DateField(auto_now_add=True, auto_now=False)
    fecha_update = models.DateField(auto_now_add=False, auto_now=True, null=True)

    class Meta:

        unique_together = ("cod_pregunta","cod_respuesta", "respuesta")
 

    def __unicode__(self):
        return self.respuesta

    def get_absolute_url(self):
        return ('listar_respuesta', [self.id, Respuestas])

apps/registro/encuestas/forms.py
#encoding:utf-8
from django.forms import ModelForm
from django import forms
from .models import Encuesta


class EncuestaForm(forms.ModelForm):
    """
    Clase de donde se define la estructura del formulario `Encuesta`
    """
    class Meta:
        model = Encuesta

apps/registro/preguntas/forms.py
#encoding:utf-8
from django.forms import ModelForm
from django import forms
from .models import Preguntas


class PreguntasForm(forms.ModelForm):
    """
    Clase de donde se define la estructura del formulario `Preguntas`
    """
    class Meta:
        model = Preguntas

apps/registro/respuestas/forms.py
#encoding:utf-8
from django.forms import ModelForm
from django import forms
from .models import Respuestas


class RespuestasForm(forms.ModelForm):
    """
    Clase de donde se define la estructura del formulario `Respuestas`
    """
    class Meta:
        model = Respuestas

apps/registro/preguntas/views.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from .models import Preguntas
from .forms import PreguntasForm
from apps.registro.encuestas.models import Encuesta
from apps.registro.respuestas.models import Respuestas
from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
import base64
import json
from django.db import connection, transaction


class RegistrarPregunta(CreateView):

    template_name = 'registro/encuesta/modificar.html'
    model = Preguntas

    def post(self, request, *args, **kwargs):
        accion = self.request.POST.get('bandera')
        cod_encuesta = self.request.POST.get('cod')
        response_data = {}
        if accion == 'encuesta':
            cod_pregunta = 1
            queryset = Preguntas.objects.all()
            queryset = queryset.filter(cod_encuesta=cod_encuesta).order_by('-cod_pregunta')[:1]
            queryset = queryset.values('cod_pregunta')

            if queryset.exists():
                cod_pregunta = queryset[0]['cod_pregunta'] + 1
            response_data['cod_pregunta'] = cod_pregunta
        else:

            form_class = self.get_form_class()
            form = self.get_form(form_class)
            add = form.save(commit=False)
            if form.is_valid():
                add.save()
                ultimo = add.id
                response_data['status'] = 'Guardado'
                response_data['id'] = ultimo
                return HttpResponse(json.dumps(response_data), content_type='application/json')
            else:
                return HttpResponse('2')
        return HttpResponse(json.dumps(response_data), content_type='application/json')


class EditarPregunta(UpdateView):
    """ Vista basada en clase: (`Editar`)

    :param template_name: ruta de la plantilla
    :param model: Modelo al cual se hace referencia
    :param success_url: nombre de la ruta a la cual se redireccionara la aplicacion una vez culminada la edicion del
        registro satisfactoriamente
    :param context_object_name: nombre del objeto que contiene esta vista
    """
    model = Preguntas
    template_name = 'registro/encuesta/modificar_pregunta.html'
    context_object_name = "editar_pregunta"
    success_url = reverse_lazy("listar_encuestas")

    def get_context_data(self, **kwargs):

        context = super(EditarPregunta, self).get_context_data(**kwargs)
        pk_pre = self.kwargs['pk']
        preguntas = Preguntas.objects.all()
        cod_enc = preguntas.filter(pk=pk_pre).values('cod_encuesta')
        encuesta = Encuesta.objects.all()
        nom_enc = encuesta.filter(pk=cod_enc)
        nombre = nom_enc[0]

        respuesta = Respuestas.objects.all()
        respuestas = respuesta.filter(cod_pregunta_id=pk_pre).values('id','cod_respuesta', 'respuesta', 'tipo')

        context['nombre_encuesta'] = nombre
        context['lista_respuestas'] = respuestas
        return context

class BorrarPreguntas(CreateView):

    def post(self, request, *args, **kwargs):
        response_data = {}
        id_reg = self.request.POST.get('id')
        Preguntas.objects.filter(id=id_reg).delete()
        existe = Preguntas.objects.filter(id=id_reg).exists()
        if existe is False:
            response_data['delete'] = 'ok'
            data = HttpResponse(json.dumps(response_data),content_type='application/json')
            return data

    def get(self, request, *args, **kwargs):
        pk_pregunta = self.kwargs['pk']

        pregunta = Preguntas.objects.get(id=pk_pregunta)
        pregunta.delete()
        return HttpResponseRedirect('/encuestas')
    

templates/registro/encuesta/encuesta.html
<!DOCTYPE html>
{% extends 'base2.html' %}

{% block contenido %}
<html>
<head>
    <title>Registrar Grupo Etareo</title>
</head>
<script type="text/javascript">
$(document).ready(function(){
	{% load templatag_grupos %}
		{% ifusergroup Web %}
			
		{% else %}
			$("#id_tipo").select2();
		{% endifusergroup %}
    $('#id_nombre').alphanumeric({allow:" +-*/=.,¡!'¿?()%:;_"}); //Valida solo valores tipo texto en descripción
    
	$('#id_tipo').change(function() {
		var tipo = $(this).val();
		
		if (tipo == 2) { //TODO
			$('#continua').prop('checked',true).prop('disabled',false)
			$('#nocontinua,#continua,#no_continua,#continua').prop('disabled',true)
		}else{ //Por Municipio
			$('#nocontinua,#continua,#no_continua,#continua').prop('disabled',false).prop('checked',false)
		}
	});
	
	$('#div_genero').on('click','div > label',function(){
		var este = $(this).attr('id');
		if (este == 'continua') {
				$('#continua').prop('checked',true);
		} else if (este == 'no_continua') {
				$('#nocontinua').prop('checked',true);
		}
	});
	
	$('#help_continua').click(function(e){
		bootbox.alert({
			title: 'Tipo de aplicación Continua',
			message: 'Las encuestas de aplicación CONTINUA, son aquellas que podrán aplicarse varias veces sin importar que los encuestados se encuentre en la misma red de computadoras.',
		})
    });
	//Mensaje de ayuda encuesta No Continua
	$('#help_nocontinua').click(function(e){
		bootbox.alert({
			title: 'Tipo de aplicación No Continua',
			message: 'Las encuestas de aplicación NO CONTINUA, son aquellas que podrán aplicarse una (1) sola vez por encuestado, sin importar que se encuentre en la misma  red ya sea de trabajo o domestica. ',
		})
    });
	
    $('#Registrar').click(function(e){ //Valida al guardar que el rago no sea menor 3 caracteres
        e.preventDefault();
		var tipo = $('#id_tipo').find('option').filter(':selected').val()
		
		var id = $(this).attr('id');
		$('input').on({
			keypress: function() {
			$(this).parent('div').removeClass('has-error');
			}
		});
		$('select').on({
			change: function() {
				$(this).parent('div').removeClass('has-error');
			}
		});
		
		if (($('#id_tipo').val() == 0)) {
			bootbox.alert("Disculpe, Debe seleccionar el tipo de Encuesta", function() {
				$('#id_tipo').parent('div').addClass('has-error'); // colocar class has-error de boostrap
				$('#id_tipo').select2('open') 
			});
		}else if ((tipo != 2) && (!$('input[name="tipo_aplicacion"]').is(':checked'))) {
			bootbox.alert('Disculpe, seleccionar el tipo de aplicación', function() {	    
			});
		}else if (($('#id_nombre').val().trim() == '')) {
			bootbox.alert("Debe colocar el nombre que llevara su encuesta", function() {
				$('#id_nombre').parent('div').addClass('has-error'); // colocar class has-error de boostrap
				$('#id_nombre').focus()
			});
		}else{
			//bootbox.alert("Registro Satisfactorio", function() {
			//});
			$('#id_estatus,#nocontinua,#continua,#no_continua,#continua').prop('disabled',false);
			$('#form_encuesta').submit();
			$('#id_estatus,#nocontinua,#continua,#no_continua,#continua').prop('disabled',true);
			
			
			//alert("Registro de nombre de encuesta con exito, a continuación procesa a registrar las preguntas")
	    
		}
    });
    $('#volver').click(function(){
        url = '/encuestas/'
        window.location = url
    })
});
</script>
<body>
    {% load templatag_grupos %}
    {% ifusergroup Registro %}
    <br/>
    <br/>

    <form id="form_encuesta" method="post" >
	{% csrf_token %}

	<div style="width: 80%;" class="panel panel-primary">
            <div class="panel-heading">
              <label class="panel-title">Registrar Encuesta</label>
            </div>
            <br/>
		<legend style="padding-bottom: 2%" class="titulo">Datos del la encuesta</legend>
	    <br/>

	    <div class="form-inline">
		
		<div class="form-group col-xs-1"></div>
		<div class="form-group col-xs-1">
		    <label>Encuesta:</label>
		</div>
		<div class="form-group col-xs-1">
		    <span style="color: red"> {{cod_encuesta}} </span>
		    
		</div>
		<div class="form-group col-xs-6"><input id="id_cod_encuesta" name="cod_encuesta" type="hidden"  value="{{cod_encuesta}}" /></div>
		
		<input id="id_estatus" name="estatus" type="hidden"  value="1" />
		<div class="form-group col-xs-1">
		    <label>Status:</label>
		</div>
		<div class="form-group col-xs-2">
		    <span id="id_estatus" name="estatus" value='' disabled="disabled" style="color: red">Borrador</span>
		</div>
		<br/>
		<br/>
		<br/>
		
		<div class="form-group col-md-1">
		</div>
		<div class="form-group col-md-1">
		    <label>Tipo:</label>
		</div>
		{% ifusergroup Web %}
		<div class="form-group col-xs-2">
		    <span name="tipo" style="color: #017F09">Web</span>
			<input id="id_tipo" name="tipo" type="hidden"  value="1" />
		</div>
		{% else%}
		<div class="form-group col-xs-2">
			<select style="width:100%;" class="form-control input-sm" id="id_tipo" name="tipo">
				<option value="0">Seleccione</option>
				<option value="1">Web</option>
				<option value="2">Móvil</option>
				<option value="3">Web y Móvil</option>
			</select>
		</div>
		{% endifusergroup %}
		<div id="div_genero" class="form-group col-md-8 text-center">
			<div class="form-group col-md-2"></div>
			<div class="form-group col-md-3">Tipo de Aplicación:</div>
			<div class="form-group col-md-3 " >
				<input type="radio" id="continua" name="tipo_aplicacion" value="1" />
				<label id="continua">Continua
				</label>
				<img id="help_continua" style="width: 18px; height: 18px;cursor: pointer" src="{{ STATIC_URL }}img/help_verde.jpg"/>
			</div>
			<div class="form-group col-md-3" >
				<input type="radio" id="nocontinua" name="tipo_aplicacion" value="2" />
				<label id="no_continua">No Continua 
				</label>
				<img id="help_nocontinua" style="width: 18px; height: 18px;cursor: pointer" src="{{ STATIC_URL }}img/help_azul.jpg"/>
			</div>
		</div>
		<br/>
		<br/>
		<br/>
		
		<div class="form-group col-xs-1"></div>
		<div class="form-group col-xs-1">
		    <label>Nombre:</label>
		</div>
		<div class="form-group col-xs-9">
		    <input id="id_nombre" maxlength="150" placeholder="Nombre de la Encuesta" style="width: 100%;font-size: 13px" name="nombre" type="text" />
		</div>
		<div class="form-group col-xs-1">
		    
		</div>
		
		
		<br/>
		<br/>
		<br/>
		<div class="row" style="text-align: center">
			<button type="button" id="volver" style="font-weight: bold;font-size: 13px" class="btn btn-warning " >
				&nbsp;<span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Volver
			</button>
			<button type="submit" id="Registrar" style="font-weight: bold;font-size: 13px" class="btn btn-info"/>
				&nbsp;<span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;Registrar Encuesta
			</button>
        </div>
		<div class="form-group col-xs-2"></div>
	    </div>
	    <br/>
	    <br/>
	    <br/>
            <br/>

	    <input id='user_create' type="hidden" name='user_create' value='{{ user.id }}'>

	    <br/>
	    <br/>
        </div>

	
	
	
	
    </form>
    {% else %}
    <p style="color: #FF0000; font-size: 18px">Disculpe No esta autorizado para esa área.</p>
    {% endifusergroup %}
</body>
</html>
{% endblock %}