apps/topologia/estados/urls.py
from django.conf.urls import patterns, include, url
from .views import RegistrarEstado, ListarEstado, EditarEstado, BorrarEstado
from django.contrib.auth.decorators import login_required


"""
    Urls para ingresar a la aplicacion estados, permitiendo visualizar los registros, crearlos, editarlos y borrarlos.
"""
urlpatterns = patterns('',
                       url(r'^$', login_required(ListarEstado.as_view(template_name="topologia/estados/listar.html"),
                                                 login_url='/'), name='listar_estado'),
                       url(r'^registrarestado/$', login_required(RegistrarEstado.as_view(template_name="topologia/estados/estados.html"),
                                                 login_url='/'), name='registrar_estado'),
                       url(r'^editarestado/(?P<pk>\d+)/$', login_required(EditarEstado.as_view(template_name="topologia/estados/modificar.html"),
                                                 login_url='/'), name='editar_estado'),
                       url(r'^borrarestado/(?P<pk>\d+)/$', login_required(BorrarEstado.as_view(template_name="topologia/estados/borrar.html"),
                                                 login_url='/'), name='borrar_estado'),
                       )

apps/topologia/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required


urlpatterns = patterns('',
                       url(r'^estados/', include('apps.topologia.estados.urls')),
                       url(r'^municipios/', include('apps.topologia.municipios.urls')),
                       url(r'^parroquias/', include('apps.topologia.parroquias.urls')),
                       url(r'^sectores/', include('apps.topologia.sectores.urls')),
                       url(r'^poligonales/', include('apps.topologia.poligonales.urls')),
                       )

apps/urls.py
from django.conf.urls import patterns, include, url
#from apps.configuraciones.views import Configuraciones

urlpatterns = patterns('',
                       #url(r'^$', include('apps.inicio.urls')),
                       url(r'^', include('apps.login.urls')),
                       url(r'^menu/', include('apps.menu.urls')),
                       url(r'^configuraciones/', include('apps.configuraciones.urls')),
                       url(r'^partidos/', include('apps.partidos.urls')),
                       url(r'^elecciones/', include('apps.elecciones.urls')),
                       url(r'^exitpoll/', include('apps.exitpoll.urls')),
                       url(r'^candidatos/', include('apps.candidatos.urls')),
                       url(r'^reportes/', include('apps.reportes.urls')),
                       url(r'^encuestas/', include('apps.registro.encuestas.urls')),
                       url(r'^preguntas/', include('apps.registro.preguntas.urls')),
                       url(r'^respuestas/', include('apps.registro.respuestas.urls')),
                       url(r'^aplicada/', include('apps.aplicada.urls')),
                       )

exit_poll/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from rest_framework.routers import DefaultRouter
from apps.topologia.estados.viewsets import EstadoViewSet
from apps.topologia.municipios.viewsets import MunicipioViewSet
from apps.topologia.parroquias.viewsets import ParroquiaViewSet
#from apps.topologia.sectores.viewsets import SectorViewSet
#from apps.topologia.poligonales.viewsets import PoligonalViewSet
from apps.circuitos.viewsets import CircuitoViewSet
from apps.grupo_etareo.viewsets import Grupo_EtareoViewSet
from apps.tipos.categoria_eleccion.viewsets import CategoriaViewSet
from apps.tipos.tipo_eleccion.viewsets import Tipo_eleccionViewSet
from apps.partidos.viewsets import PartidosViewSet
from apps.elecciones.viewsets import EleccionViewSet
from apps.exitpoll.viewsets import ExitPollViewSet
from apps.registro.encuestas.viewsets import EncuestaViewSet
from apps.candidatos.viewsets import CandidatosViewSet
from apps.registro.preguntas.viewsets import PreguntasViewSet
from apps.registro.respuestas.viewsets import RespuestasViewSet
import settings


router = DefaultRouter()
router.register(r'estado', EstadoViewSet)
router.register(r'municipio', MunicipioViewSet)
router.register(r'parroquia', ParroquiaViewSet)
#router.register(r'sector', SectorViewSet)
#router.register(r'poligonal', PoligonalViewSet)
router.register(r'circuito', CircuitoViewSet)
router.register(r'grupo_etareo', Grupo_EtareoViewSet)
router.register(r'categoria_eleccion', CategoriaViewSet)
router.register(r'tipo_eleccion', Tipo_eleccionViewSet)
router.register(r'partidos', PartidosViewSet)
router.register(r'elecciones', EleccionViewSet)
router.register(r'exitpoll', ExitPollViewSet)
router.register(r'candidatos', CandidatosViewSet)
router.register(r'encuestas', EncuestaViewSet)
router.register(r'preguntas', PreguntasViewSet)
router.register(r'respuestas', RespuestasViewSet)

urlpatterns = patterns('',
                       url(r'^chaining/', include('pixelfields_smart_selects.urls')),
                       url(r'^admin/', include(admin.site.urls)),
		       url(r'^login/', include('apps.login.urls')),
                       url(r'^api/', include(router.urls)),
                       url(r'^', include('apps.urls')),
                       url(r'^imagenes/(?P<path>.*)$', 'django.views.static.serve',
                           {'document_root': settings.MEDIA_ROOT}),
		       url(r'^', include('apps.exitpoll.urls')),
                       url(r'^', include('apps.votacion.urls')),
                       url(r'^reporte/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_PDF}),
		       url(r'^temporal/', include('apps.temporal.urls')),
                       )

apps/topologia/estados/models.py
from django.db import models


class Estado(models.Model):
    """ Clase que define todo lo referente a los `Estados`:
    Registrar, Modificar, Eliminar y Consultar

    :param IntegerField cod_estado: campo donde se coloca el codigo del Estado.
    :param CharField estado: campo donde ingresas el nombre del Estado.
    """

    cod_estado = models.IntegerField(unique=True, null=True)
    estado = models.CharField(max_length=50, unique=True)

    class Meta:
        """ Ordena los registros en base a el campo cod_estado."""
        ordering = ('cod_estado',)  # Ordenado por

    def __unicode__(self):
        return self.estado

    def get_absolute_url(self):
        return ('listar_estado', [self.id, ])

apps/topologia/municipios/models.py
from django.db import models
from apps.topologia.estados.models import Estado
from apps.circuitos.models import Circuito


class Municipio(models.Model):
    """ Clase que define todo lo referente a los `Municipios`:
    Registrar, Modificar, Eliminar y Consultar

    :param ForeignKey estado: campo que llama al modelo Estado.
    :param IntegerField circuito: campo que a traves de ajax carga los circuitos asociados a los estados.
    :param IntegerField cod_municipio: campo donde se coloca el codigo del Municipio.
    :param CharField municipio: campo donde ingresas el nombre del Municipio
    """
    estado = models.ForeignKey(Estado, to_field='cod_estado', on_delete=models.SET_NULL,
                               related_name='estado_municipio', null=True)
    circuito = models.IntegerField(null=True)
    cod_municipio = models.IntegerField(null=True)
    municipio = models.CharField(max_length=50, null=True)

    def __unicode__(self):
        return self.municipio

    class Meta:
        """
        :param unique_together: atributo que valida que el nombre y el codigo de municipio sea unico por estado
        :param ordering: Ordena los registros en base a el campo estado y sus municicipios
        """
        unique_together = ("estado", "circuito", "cod_municipio", "municipio")
        ordering = ('estado', 'municipio')

    def get_absolute_url(self):
        return ('listar_municipio', [self.id, ])

apps/topologia/parroquias/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''Modelo Parroquia del país'''
from django.db import models
from smart_selects.db_fields import ChainedForeignKey 
from apps.topologia.estados.models import Estado
from apps.topologia.municipios.models import Municipio


class Parroquia(models.Model):
    """ Clase que define todo lo referente a las `Parroquias`:
    Registrar, Modificar, Eliminar y Consultar

    :param ForeignKey estado: campo que llama al modelo Estado.
    :param IntegerField municipio: campo que a traves de ajax carga los municipios asociados al estado.
    :param IntegerField cod_parroquia: campo donde se coloca el codigo de la Parroquia.
    :param CharField parroquia: campo donde ingresas el nombre de la Parroquia
    """
    parroquia = models.CharField(max_length=50)
    estado = models.ForeignKey(Estado, to_field='cod_estado', on_delete=models.SET_NULL, related_name='estado_parroquia', null=True)
    cod_parroquia = models.IntegerField(null=True)
    municipio = models.IntegerField(null=True)

    def __unicode__(self):
        """ Representacion en cadena de la clase Parroquia. """
        return self.parroquia

    class Meta:
        """
        :param unique_together: atributo que valida que la parroquia sea unica por municipio y a su ves al estado
        :param ordering: Ordena los registros en base a el campo estado, municicipios y parroquia
        """
        unique_together = ("estado", "municipio", "parroquia")  # Municipio unico por Estado seleccionado
        ordering = ('estado', 'municipio', 'parroquia')  # Ordenado por

    def get_absolute_url(self):
        """ La Url de vista principal de administracion de Parroquia. """
        return ('listar_parroquia', [self.id, ])

apps/topologia/sectores/models.py
# -*- coding: utf-8 -*-
'''Modelo para el Registro Sectores'''
from django.db import models
from smart_selects.db_fields import ChainedForeignKey
from apps.topologia.estados.models import Estado
from apps.topologia.municipios.models import Municipio
from apps.topologia.parroquias.models import Parroquia
from django.contrib.auth.models import User


class Sector(models.Model):
    """ Clase que define todo lo referente a las `Centros`:
    Registrar, Modificar, Eliminar y Consultar

    :param CharField sector: campo donde registra el nombre del sector.
    :param ForeignKey estado: campo que llama al modelo Estado.
    :param IntegerField municipio: campo que a traves de ajax carga los municipios asociados al estado.
    :param IntegerField parroquia: campo que a traves de ajax carga las parroquia asociados a los municipios.
    :param CharField cod_s: campo para colocar el codigo del sector.
    :param ForeignKey user_create: campo que llama al modelo User.
    :param ForeignKey user_update: campo que llama al modelo User.
    :param DateTimeField fecha_create: campo de tipo tiempo que captura fecha y hora.
    :param DateTimeField fecha_update: campo de tipo tiempo que captura fecha y hora.
    """

    cod_s = models.IntegerField(verbose_name="Código del Sector", max_length=2)
    sector = models.CharField(verbose_name="Sector", max_length=150)
    estado = models.ForeignKey(Estado, to_field='cod_estado', on_delete=models.SET_NULL,
                               related_name='estado_sectores', null=True)
    municipio = models.IntegerField(null=True)
    parroquia = models.IntegerField(null=True)
    #Auditoria
    user_create = models.ForeignKey(User, null=True, blank=True, related_name='+')
    user_update = models.ForeignKey(User, null=True, blank=True, related_name='+')
    fecha_create = models.DateTimeField(auto_now_add=True, auto_now=False)
    fecha_update = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)

    class Meta:
        """
        :param unique_together: verifica que no existan centros repetidos en base a su nombre codigo estado
            municipio y parroquia
        :param ordering: Ordena los registros en base a el campo cod_n nombre estado
        """
        unique_together = ("cod_s", "sector", "estado", "municipio", "parroquia")
        ordering = ('cod_s', 'sector', 'estado', 'municipio', 'parroquia')

    def __unicode__(self):
        return self.sector

    def get_absolute_url(self):
        return ('listar_sector', [self.id, Sector])

apps/topologia/estados/forms.py
#encoding:utf-8
from django.forms import ModelForm
from django import forms
from .models import Estado


class EstadoForm(forms.ModelForm):
    """ Clase de donde se define la estructura del formulario `Estado`."""

    class Meta:
        """
        Llamado del modelo
        """
        model = Estado

apps/topologia/municipios/forms.py
#encoding:utf-8
from django.forms import ModelForm
from django import forms
from .models import Municipio


class MunicipioForm(forms.ModelForm):
    """ Clase de donde se define la estructura del formulario `Municipio`."""
    class Meta:
        """
        Llamado del modelo
        """
        model = Municipio

apps/topologia/parroquias/forms.py
#encoding:utf-8
from django.forms import ModelForm
from django import forms
from .models import Parroquia


class ParroquiaForm(forms.ModelForm):
    """ Clase de donde se define la estructura del formulario `Parroquia`."""
    class Meta:
        model = Parroquia

apps/topologia/poligonales/forms.py
#encoding:utf-8
from django.forms import ModelForm
from django import forms
from .models import Poligonal


class PoligonalForm(forms.ModelForm):
    """ Clase de donde se define la estructura del formulario `Poligonal`."""
    class Meta:
        model = Poligonal

apps/topologia/sectores/forms.py
#encoding:utf-8
from django.forms import ModelForm
from django import forms
from .models import Sector


class SectorForm(forms.ModelForm):
    """ Clase de donde se define la estructura del formulario `Sector`."""
    class Meta:
        model = Sector

apps/topologia/estados/views.py
#encoding:utf-8
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, FormView
from django.core.urlresolvers import reverse_lazy
from .models import Estado
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from .forms import EstadoForm
from django.contrib.auth.models import Group, Permission, User
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from django.utils.decorators import method_decorator
from apps.circuitos.models import Circuito


class RegistrarEstado(CreateView):
    """ Vista basada en clase: (`Registrar`)

    :param template_name: ruta de la plantilla
    :param model: Modelo al cual se hace referencia
    :param success_url: nombre de la ruta a la cual se redireccionara la aplicacion una vez culminado el registro
        satisfactoriamente
    :param form_class: nombre de la clase Formulario
    """
    template_name = 'topologia/estados/estados.html'
    model = Estado
    success_url = reverse_lazy("listar_estado")
    form_class = EstadoForm

    def post(self, request, *args, **kwargs):
        bandera = request.POST.get('bandera')
        cod_estado = request.POST.get('cod_estado')
        estado = request.POST.get('estado')
        existe = Estado.objects.filter(estado=estado).exists()
        existe_c = Estado.objects.filter(cod_estado=cod_estado).exists()
        if existe and bandera == 'true':
            return HttpResponse('existe')
        elif existe_c and bandera == 'true':
            return HttpResponse('existe_c')
        else:
            form_class = self.get_form_class()
            form = self.get_form(form_class)
            if form.is_valid():
                form.save()
            return HttpResponseRedirect('/configuraciones/topologia/estados/')


class ListarEstado(ListView):
    """ Vista basada en clase: (`Listar`)

    :param template_name: ruta de la plantilla
    :param model: Modelo al cual se hace referencia
    :param context_object_name: nombre del objeto que contiene esta vista
    
    """
    model = Estado
    template_name = 'topologia/estados/listar.html'
    context_object_name = "listar_estado"


class EditarEstado(UpdateView):
    """ Vista basada en clase: (`Editar`)

    :param template_name: ruta de la plantilla
    :param model: Modelo al cual se hace referencia
    :param success_url: nombre de la ruta a la cual se redireccionara la aplicacion una vez culminada la edición del
        registro satisfactoriamente
    :param context_object_name: nombre del objeto que contiene esta vista
    """
    model = Estado
    template_name = 'topologia/estados/modificar.html'
    context_object_name = "editar_estado"
    success_url = reverse_lazy("listar_estado")


class BorrarEstado(DeleteView):
    """ Vista basada en clase: (`Borrar`)

    :param template_name: ruta de la plantilla
    :param model: Modelo al cual se hace referencia
    :param success_url: nombre de la ruta a la cual se redireccionara la aplicacion una vez eliminado el registro
        satisfactoriamente
    :param context_object_name: nombre del objeto que contiene esta vista
    """
    model = Estado
    template_name = 'topologia/estados/borrar.html'
    context_object_name = "borrar_estado"
    success_url = reverse_lazy("listar_estado")

    def get_context_data(self, **kwargs):
        context = super(BorrarEstado, self).get_context_data(**kwargs)
        pk_est = self.kwargs['pk']
        estado = Estado.objects.all()
        id_est = estado.filter(pk=pk_est).values('cod_estado')

        cir = Circuito.objects.all()
        existe = cir.filter(estado_id=id_est)
        cantidad = len(existe)

        context['cantidad'] = cantidad
        return context

templates/topologia/parroquias/borrar.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block contenido %}
<html>
<head>
    <title>Eliminar Parroquia</title>
</head>
{% load templatag_grupos %}
{% ifusergroup Topologia %}
<script>
$(document).ready(function() {
    $('#volver,#eliminar').click(function(){
        url = '/configuraciones/topologia/parroquias'
        window.location = url
    })
});

</script>
<body>
    
    <form method="post">{% csrf_token %}
    </br>
    </br>
    <label class="tit-elim">Eliminar Parroquia</label>
   
	<h3>¿Está seguro que quiere borrar esta Parroquia "{{ borrar_parroquia }}" ?</h3>
	{% if cantidad_s > 0 %}
	    <h4>Disculpe, pero no puede Eliminar esta Parroquia porque ya esta <span style="color: red"> vinculado a 1 o más Sectores</span></h4>
	{% endif%}
	<button style="font-weight: bold;font-size: 13px" type="button" id="volver" class="btn btn-warning"/>
	    <span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Volver
	</button>
	<button style="font-weight: bold" type="submit" id="eliminar" class="btn btn-danger "
	    {% if cantidad_s > 0  %}
		disabled="disabled"
	    {% endif %}
	    /> <span class="glyphicon glyphicon-remove"></span>&nbsp;Eliminar
	</button>
	
    </form>
</body>
{% else %}
<p style="color: #FF0000; font-size: 18px">Disculpe No esta autorizado para esa área.</p>
{% endifusergroup %}
</html>
{% endblock %}

templates/topologia/parroquias/listar.html
{% extends 'base.html' %}

{% block contenido %}
<script>
$(document).ready(function(){
    var TUbch = $('#tab_parroquia').dataTable({
        "iDisplayLength": 25,
        "iDisplayStart": 0,
        "sPaginationType": "full_numbers",
        "aLengthMenu": [25, 50, 75, 100],
        "oLanguage": {"sUrl": "/static/js/es.txt"},
        "aoColumns": [
            {"sClass": "registro center", "sWidth": "10%"},
            {"sClass": "registro center", "sWidth": "15%"},
            {"sClass": "registro center", "sWidth": "5%"},
            {"sClass": "registro center", "sWidth": "15%"},
            {"sWidth": "3%", "bSortable": false, "sClass": "center sorting_false", "bSearchable": false},
            {"sWidth": "3%", "bSortable": false, "sClass": "center sorting_false", "bSearchable": false},
        ]
    });
    $('#enviar').click(function(){
        url = '/configuraciones/topologia/parroquias/registrarparroquia/'
        window.location = url
    })   

});
</script>
{% load templatag_grupos %}
{% ifusergroup Topologia %}
<div style="width:80%">
    <button role="button" class="btn btn-primary" style="font-weight: bold;font-size: 13px" id="enviar" >
        &nbsp;<span class="glyphicon glyphicon-plus"></span>&nbsp;Agregar Parroquia
    </button>
    </br>
    </br>
    
    <table style="width:100%;" border="0" align="center" cellspacing="1" id="tab_parroquia" align="center"
       class="table table-bordered table-striped table-hover table-condensed dt-responsive table-responsive" style="width:30%">
    <thead style="font-size: 16px">
        <tr class="info">
            <th style='text-align: center' colspan="6">Listado de Parroquias</th>
        </tr>
        <tr class="info">
            <th style='text-align: center'>Estado</th>
            <th style='text-align: center'>Municipio</th>
            <th style='text-align: center'>Código</th>
            <th style='text-align: center'>Parroquia</th>
            <th style='text-align: center'>Editar</th>
            <th style='text-align: center'>Borrar</th>
        </tr>
    </thead>
    <tbody>
        {% for m in listar_parroquia %}
        <tr style="font-size: 16px" class="{% cycle 'impar' 'par' %}">
            <td>
                {{m.estado}}
            </td>
            <td>   
                {% for c in list_m %}
                    {% if c.estado_id == m.estado_id and c.cod_municipio == m.municipio %}
                        {{c.municipio}}
                    {% endif %}
                {% endfor %}
            </td>
            <td>
                {{m.cod_parroquia}}
            </td>
            <td>
                {{m.parroquia}}
            </td>
            <td style='text-align: center'>
                <a href="{% url "editar_parroquia" m.id %}"><img style="width:25px;height: 25px" src="{{ STATIC_URL }}img/edit.png"/></a>
            </td>
            <td style='text-align: center'>
                <a href="{% url "borrar_parroquia" m.id %}"><img style="width:25px;height: 25px" src="{{ STATIC_URL }}img/borrar.png"/></a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% else %}
<p style="color: #FF0000; font-size: 18px">Disculpe No esta autorizado para esa área.</p>
{% endifusergroup %}
{% endblock %}

templates/topologia/parroquias/modificar.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block contenido %}
<html>
<head>
    <title>Editar Parroquia</title>
</head>
<script type="text/javascript">
$(document).ready(function(){
    $("#id_cod_estado,#id_cod_municipio").select2();
    $('#id_parroquia').alpha({allow:" "},{allcaps:true}); //Valida solo valores tipo texto
    $('#id_cod_parroquia').numeric(); //Valida solo valores tipo numero
    $('#registrar').click(function(e){ //Valida al guardar que el rago no sea menor 5 caracteres
	e.preventDefault();
	
	$('select').on({
	    change: function() {
		$(this).parent('div').removeClass('has-error');
	    }
	});
	$('input').on({
	    keypress: function() {
		$(this).parent('div').removeClass('has-error');
	    }
	});
	var municipio = $('#id_cod_municipio').find('option').filter(':selected').val()

	if (($('#id_parroquia').val().length < 4)) {
	    bootbox.alert('Disculpe, Nombre de Parroquia invalido (Muy Corto)', function() {	    
		$('#id_parroquia').parent('div').addClass('has-error');
	    });
	}
	else if (($('#id_parroquia').val() == '')) {
	    bootbox.alert('Disculpe, Debe Introducir el nombre de la Parroquia', function() {	    
		$('#id_parroquia').parent('div').addClass('has-error');
	    });
	}
	else if($('#id_parroquia').val() == null ||  $('#id_parroquia').val().length == 0 || /^\s+$/.test($('#id_parroquia').val())) {
             bootbox.alert('Disculpe, no esta registrando nada', function() {	    
		$('#id_parroquia').parent('div').addClass('has-error');
	    });
	}
	else if (municipio == 0) {
	    bootbox.alert('Disculpe, Seleccionar el Municipio', function() {	    
		$('#id_cod_municipio').parent('div').addClass('has-error');
	    });
	}

        else {
	    $('#id_cod_parroquia,#id_cod_estado').prop('disabled',false);
	    $('form').submit();
	    $('#id_cod_parroquia,#id_cod_estado').prop('disabled',true);
        }
    });
    $('#volver').click(function(){
        url = '/configuraciones/topologia/parroquias/'
        window.location = url
    })
});
</script>

<body>
    {% load templatag_grupos %}
    {% ifusergroup Topologia %}  
    <form method="post">
	{% csrf_token %}
    </br>
    
	<div style="width: 80%;" class="panel panel-primary">
            <div class="panel-heading">
              <label class="panel-title">Modificar Parroquia</label>
            </div>
            <br/>
	   
	    <fieldset><legend class="titulo">Datos de la Parroquia</legend></fieldset>
	    <div class="form-inline" style="text-align: left;font-weight: bold">
		<div class="form-group col-xs-6">
		    <label>C&oacute;digo:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
		    <input style="width: 70%" id="id_cod_parroquia" disabled="disabled" maxlength="2" name="cod_parroquia" value='{{obj_reg_parr.cod_parroquia}}' type="text"  />
		</div>
		<div class="form-group col-xs-6">
		    <label>Parroquia:&nbsp;&nbsp;</label>
		    <input style="width: 70%"  id="id_parroquia" maxlength="50" name="parroquia" type="text" value='{{obj_reg_parr.parroquia}}' />
		</div>
	    </div>
	    
	    <br/>
	    <br/>
	    <br/>
	    <div class="form-inline" >
		<div class="form-group col-xs-6">
		    <label>Estado:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
		    <select id="id_cod_estado" name="estado" disabled="disabled" style="width: 70%" class="form-control select2 input-sm" >
			<option value="">-----------------------------</option>
			{% for e in list_e %}
			    {% if e.cod_estado == obj_reg_parr.estado_id%}
				<option value='{{e.cod_estado}}' selected='selected'>{{ e.estado }}</option>
			    {% endif %}
			    {% if not e.cod_estado == obj_reg_parr.estado_id %}
				<option value='{{e.cod_estado}}'>{{ e.estado }}</option>
			    {% endif %}
			{% endfor %}
		    </select>
		</div>
		<div class="form-group col-xs-6">
		    <label>Municipio:&nbsp;&nbsp;</label>
		    <select id="id_cod_municipio" class="form-control select2 input-sm" style="width: 70%" name="municipio" >
			<option value="" selected="selected">----------------------------</option>
			{% for est in list_e%}
			    {% for m in list_m %}
				{% if est.cod_estado == obj_reg_parr.estado_id and m.cod_municipio == obj_reg_parr.municipio%}
				    <option value='{{m.cod_municipio}}' selected='selected'>{{m.municipio}}</option>
				{% endif %}
				{% if not m.cod_municipio == obj_reg_parr.municipio %}
				    <option value='{{m.cod_municipio}}'>{{m.municipio}}</option>
				{% endif %}
			    {% endfor %}
			{%endfor%}
		    </select>
		</div>
            </div>
	    
	    <br/>
	    <br/>
	    <br/>
	    <div class="row" style="text-align: center">
		<button type="button" id="volver" style="font-weight: bold;font-size: 13px" class="btn btn-warning " >
		    &nbsp;<span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Volver
		</button>
		<button type="submit" id="registrar" style="font-weight: bold;font-size: 13px" class="btn btn-info"/>
		    &nbsp;<span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;Guardar Cambios
		</button>
	    </div>
            <br/>
        </div>
    </form>
    {% else %}
    <p style="color: #FF0000; font-size: 18px">Disculpe No esta autorizado para esa área.</p>
    {% endifusergroup %}
</body>
</html>
{% endblock %}